-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4ECbiSmICF2AuVJl
kFeCrXiZrdVnZDcLWjpmXKprSMmgCgYIKoZIzj0DAQehRANCAAToK0rjmiX8dEqI
fYlvVugLG6YeT+EvDNPUFRwMJUUu485Ybe9hW8NfDwtt0AAAB/bprg21HXMXNNZd
LpT6BtM2
-----END PRIVATE KEY-----