# Generated by Django 5.2.7 on 2025-12-24 17:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', max_length=20)),
                ('image', models.ForeignKey(blank=True, help_text='Optional image for the question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='CMSAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(help_text='Answer text')),
                ('is_correct', models.BooleanField(default=False, help_text='Check if this is the correct answer')),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation for this answer')),
                ('question', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cms.cmsquestion')),
            ],
            options={
                'verbose_name': 'Answer Option',
                'verbose_name_plural': 'Answer Options',
            },
        ),
        migrations.CreateModel(
            name='CMSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('passing_percentage', models.PositiveIntegerField(default=100, help_text='Percentage needed to pass (0-100)')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Time limit in seconds (leave empty for no limit)', null=True)),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Maximum allowed attempts (leave empty for unlimited)', null=True)),
                ('shuffle_questions', models.BooleanField(default=False, help_text='Randomize question order for each attempt')),
                ('shuffle_answers', models.BooleanField(default=False, help_text='Randomize answer order for each attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='test',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cms.cmstest'),
        ),
    ]
