# Generated by Django 5.2.7 on 2025-12-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsquestion_cmsanswer_cmstest_cmsquestion_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsanswer',
            options={'ordering': ('order',), 'verbose_name': 'Answer Option', 'verbose_name_plural': 'Answer Options'},
        ),
        migrations.AlterModelOptions(
            name='cmsquestion',
            options={'ordering': ('order',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='cmsanswer',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='cmsquestion',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='cmsanswer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='cmsanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cms.cmsquestion'),
        ),
        migrations.AlterField(
            model_name='cmsquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cms.cmstest'),
        ),
    ]
