# Generated by Django 5.2.7 on 2026-01-14 06:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_cmsanswer_options_alter_cmsquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsanswer',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cms.cmsquestion'),
        ),
        migrations.AlterField(
            model_name='cmsquestion',
            name='test',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cms.cmstest'),
        ),
    ]
