# Generated by Django 5.2.7 on 2026-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_cmstest_description_en_cmstest_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsanswer',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Text (English)'),
        ),
        migrations.AddField(
            model_name='cmsanswer',
            name='text_es',
            field=models.TextField(blank=True, verbose_name='Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='cmsanswer',
            name='text_hi',
            field=models.TextField(blank=True, verbose_name='Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='cmsanswer',
            name='text_hy',
            field=models.TextField(blank=True, verbose_name='Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='cmsanswer',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Text (Russian)'),
        ),
        migrations.AddField(
            model_name='cmsanswer',
            name='text_zh',
            field=models.TextField(blank=True, verbose_name='Text (Chinese)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='Explanation (English)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='explanation_es',
            field=models.TextField(blank=True, verbose_name='Explanation (Spanish)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='explanation_hi',
            field=models.TextField(blank=True, verbose_name='Explanation (Hindi)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='explanation_hy',
            field=models.TextField(blank=True, verbose_name='Explanation (Armenian)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='explanation_ru',
            field=models.TextField(blank=True, verbose_name='Explanation (Russian)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='explanation_zh',
            field=models.TextField(blank=True, verbose_name='Explanation (Chinese)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Text (English)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='text_es',
            field=models.TextField(blank=True, verbose_name='Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='text_hi',
            field=models.TextField(blank=True, verbose_name='Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='text_hy',
            field=models.TextField(blank=True, verbose_name='Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Text (Russian)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='text_zh',
            field=models.TextField(blank=True, verbose_name='Text (Chinese)'),
        ),
    ]
