# Generated by Django 5.2.7 on 2026-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_multilingual_fields_to_questions_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsanswer',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='cmsquestion',
            name='explanation_en',
        ),
        migrations.RemoveField(
            model_name='cmsquestion',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='cmstest',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='cmstest',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='cmsanswer',
            name='text',
            field=models.TextField(help_text='Answer text (English)'),
        ),
        migrations.AlterField(
            model_name='cmsquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer (English)'),
        ),
        migrations.AlterField(
            model_name='cmsquestion',
            name='text',
            field=models.TextField(help_text='Question text (English)'),
        ),
        migrations.AlterField(
            model_name='cmstest',
            name='description',
            field=models.TextField(blank=True, help_text='English description'),
        ),
        migrations.AlterField(
            model_name='cmstest',
            name='title',
            field=models.CharField(help_text='English title', max_length=255),
        ),
    ]
