# Generated by Django 5.2.7 on 2026-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_en_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmstest',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AddField(
            model_name='cmstest',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (drag to reorder)'),
        ),
    ]
