# Generated by Django 5.2.7 on 2026-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_cmstest_options_cmstest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmstest',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Whether this test is a demo test (accessible without subscription)'),
        ),
    ]
