# Generated by Django 5.2.7 on 2026-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_cmstest_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsquestion',
            name='video',
            field=models.FileField(blank=True, help_text='Video for the question (if any)', null=True, upload_to='test_questions/videos/'),
        ),
    ]
