# Generated by Django 5.2.7 on 2026-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_add_video_to_cmsquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmstest',
            name='mixed_question_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of random questions to pull from this test for the mixed screening test. Set 0 to exclude.'),
        ),
    ]
