# Generated by Django 5.2.7 on 2026-06-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_add_mixed_question_count_to_cmstest'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmstest',
            name='image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image (Spanish)'),
        ),
        migrations.AddField(
            model_name='cmstest',
            name='image_hi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image (Hindi)'),
        ),
        migrations.AddField(
            model_name='cmstest',
            name='image_hy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image (Armenian)'),
        ),
        migrations.AddField(
            model_name='cmstest',
            name='image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image (Russian)'),
        ),
        migrations.AddField(
            model_name='cmstest',
            name='image_zh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image (Chinese)'),
        ),
    ]
