# Generated by Django 5.2.7 on 2026-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_cmstest_image_es_cmstest_image_hi_cmstest_image_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsquestion',
            name='video_es',
            field=models.FileField(blank=True, null=True, upload_to='test_questions/videos/', verbose_name='Video (Spanish)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='video_hi',
            field=models.FileField(blank=True, null=True, upload_to='test_questions/videos/', verbose_name='Video (Hindi)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='video_hy',
            field=models.FileField(blank=True, null=True, upload_to='test_questions/videos/', verbose_name='Video (Armenian)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='test_questions/videos/', verbose_name='Video (Russian)'),
        ),
        migrations.AddField(
            model_name='cmsquestion',
            name='video_zh',
            field=models.FileField(blank=True, null=True, upload_to='test_questions/videos/', verbose_name='Video (Chinese)'),
        ),
    ]
