# Generated by Django 5.2.7 on 2025-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True, unique=True),
        ),
    ]
