# Generated by Django 5.2.7 on 2025-12-15 16:24

from django.db import migrations


def clean_empty_stripe_customer_ids(apps, schema_editor):
    """Convert empty string stripe_customer_id values to NULL."""
    Subscription = apps.get_model('accounts', 'Subscription')
    # Update all subscriptions with empty string to NULL
    Subscription.objects.filter(stripe_customer_id='').update(stripe_customer_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_null_to_stripe_customer_id'),
    ]

    operations = [
        migrations.RunPython(clean_empty_stripe_customer_ids, reverse_code=migrations.RunPython.noop),
    ]
