# Generated by Django 5.2.7 on 2025-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clean_empty_stripe_customer_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Single-use token for password reset', max_length=64, null=True),
        ),
    ]
