# Generated by Django 5.2.7 on 2025-12-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailotp_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='reset_token',
        ),
    ]
