# Generated by Django 5.2.7 on 2026-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_emailotp_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days of access (7/30/90)', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_one_time_purchase',
            field=models.BooleanField(default=False, help_text='True for one-time purchase, False for recurring subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_tier',
            field=models.CharField(blank=True, choices=[('starter', 'Starter - 7 Days'), ('standard', 'Standard - 30 Days'), ('premium', 'Premium - 90 Days')], help_text='Plan tier (starter/standard/premium)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID that user purchased', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID (for recurring) or Payment Intent ID (for one-time)', max_length=255, null=True, unique=True),
        ),
    ]
