# Generated by Django 5.2.7 on 2026-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_expired_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Billing interval in days (7/30/90)', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_one_time_purchase',
            field=models.BooleanField(default=False, help_text='Deprecated - always False for recurring subscriptions'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe recurring Price ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True, unique=True),
        ),
    ]
