# Generated by Django 5.2.7 on 2026-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_subscription_access_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple')], default='email', help_text='How the user originally registered', max_length=10),
        ),
    ]
