# Generated by Django 5.2.7 on 2026-02-24 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_auth_provider_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe PaymentMethod ID (e.g. pm_xxx)', max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (visa, mastercard, amex, etc.)', max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=4, null=True)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, help_text='Card expiration month (1-12)', null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, help_text='Card expiration year', null=True)),
                ('billing_name', models.CharField(blank=True, help_text='Cardholder / billing name', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='accounts_pa_user_id_fcb474_idx'), models.Index(fields=['stripe_payment_method_id'], name='accounts_pa_stripe__53d88f_idx')],
            },
        ),
    ]
