# Generated by Django 5.2.7 on 2026-08-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_payment_method_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_sub',
            field=models.CharField(blank=True, help_text="Apple's stable user identifier (sub claim) for Sign in with Apple", max_length=255, null=True, unique=True),
        ),
    ]
