# Generated by Django 5.2.7 on 2025-11-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lesson category',
                'verbose_name_plural': 'Lesson categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Image for the question (if any)', null=True, upload_to='test_questions/')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of the question in the test')),
                ('points', models.PositiveIntegerField(default=1, help_text='How many points this question is worth')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('theory', 'Theory'), ('mixed', 'Video + theory')], default='video', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='learning.lessoncategory')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for why this option is correct/incorrect (can be shown after answering)')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of the answer option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='learning.question')),
            ],
            options={
                'verbose_name': 'Answer option',
                'verbose_name_plural': 'Answer options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Time limit in seconds (if any)', null=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Marks this test as a demo test')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.test'),
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('lesson_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='learning.lessoncategory')),
            ],
            options={
                'verbose_name': 'Test category',
                'verbose_name_plural': 'Test categories',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='learning.testcategory'),
        ),
    ]
