# Generated by Django 5.2.7 on 2025-12-06 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson progress',
                'verbose_name_plural': 'Lesson progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Test answer',
                'verbose_name_plural': 'Test answers',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total_points', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField()),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, help_text='Time taken to complete the test in seconds', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Test attempt',
                'verbose_name_plural': 'Test attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['category', 'order', 'id'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='answeroption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order within category'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed attempts (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=70, help_text='Percentage needed to pass (0-100)'),
        ),
        migrations.AddField(
            model_name='test',
            name='shuffle_answers',
            field=models.BooleanField(default=False, help_text='Randomize answer order for each attempt'),
        ),
        migrations.AddField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for each attempt'),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['category', 'order'], name='learning_le_categor_501a76_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['category', 'slug'], name='learning_le_categor_e4febf_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='learning_le_lesson__038019_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['test_category', 'is_demo'], name='learning_te_test_ca_e7b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['lesson'], name='learning_te_lesson__26bfce_idx'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_answer_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 1)), name='question_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('passing_percentage__gte', 0), ('passing_percentage__lte', 100)), name='test_passing_percentage_range'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, help_text='The answer option selected by the user (null if skipped)', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.answeroption'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.test'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.testattempt'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'completed'], name='learning_le_user_id_87f14b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'completed'], name='learning_le_lesson__a9cd18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', '-started_at'], name='learning_te_user_id_581211_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'passed'], name='learning_te_user_id_25befa_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', '-started_at'], name='learning_te_test_id_876b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='testanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='learning_te_attempt_269fae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
