# Generated by Django 5.2.7 on 2025-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonprogress_testanswer_testattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Percentage needed to pass (0-100)'),
        ),
    ]
