# Generated by Django 5.2.7 on 2025-12-13 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_test_passing_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite lesson',
                'verbose_name_plural': 'Favorite lessons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='learning_fa_user_id_61ae9e_idx'), models.Index(fields=['lesson'], name='learning_fa_lesson__296b0c_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
