# Generated by Django 5.2.7 on 2025-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_favoritelesson'),
        ('onboarding', '0006_vehicle_image_vehicle_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='states',
            field=models.ManyToManyField(blank=True, help_text='States where this lesson is available. Leave empty for all states.', related_name='lessons', to='onboarding.state'),
        ),
        migrations.AddField(
            model_name='test',
            name='states',
            field=models.ManyToManyField(blank=True, help_text='States where this test is available. Leave empty for all states.', related_name='tests', to='onboarding.state'),
        ),
    ]
