# Generated by Django 5.2.7 on 2025-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_lesson_states_test_states'),
        ('onboarding', '0006_vehicle_image_vehicle_image_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcategory',
            name='lesson_category',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_category',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='learning_le_categor_501a76_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='learning_le_categor_e4febf_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='learning_te_test_ca_e7b9d3_idx',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order'], name='learning_le_order_5b7c64_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['slug'], name='learning_le_slug_39551e_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_demo'], name='learning_te_is_demo_76ff88_idx'),
        ),
        migrations.DeleteModel(
            name='LessonCategory',
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
    ]
