# Generated by Django 5.2.7 on 2025-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the test', null=True, upload_to='test_images/'),
        ),
    ]
