# Generated by Django 5.2.7 on 2025-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_add_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, help_text='Video for the question (if any)', null=True, upload_to='test_questions/videos/'),
        ),
    ]
