# Generated by Django 5.2.7 on 2025-12-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_question_video'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test',
            name='learning_te_lesson__26bfce_idx',
        ),
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.OneToOneField(blank=True, help_text='Test associated with this lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_lesson', to='learning.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_test', to='learning.lesson'),
        ),
    ]
