# Generated by Django 5.2.7 on 2025-12-17 09:44

from django.db import migrations


def copy_lesson_test_relationship(apps, schema_editor):
    """Copy the relationship from Test.lesson to Lesson.test"""
    Lesson = apps.get_model('learning', 'Lesson')
    Test = apps.get_model('learning', 'Test')
    
    # For each test that has a lesson, set the lesson's test field
    for test in Test.objects.filter(lesson__isnull=False):
        lesson = test.lesson
        lesson.test = test
        lesson.save()


def reverse_copy_lesson_test_relationship(apps, schema_editor):
    """Reverse the relationship copy (for migration rollback)"""
    Lesson = apps.get_model('learning', 'Lesson')
    
    # Clear the test field from all lessons
    Lesson.objects.update(test=None)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_add_test_to_lesson'),
    ]

    operations = [
        migrations.RunPython(copy_lesson_test_relationship, reverse_copy_lesson_test_relationship),
    ]
