# Generated by Django 5.2.7 on 2025-12-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_copy_lesson_test_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='test',
            field=models.OneToOneField(blank=True, help_text='Test associated with this lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='learning.test'),
        ),
    ]
