# Generated by Django 5.2.7 on 2025-12-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_remove_lesson_video_url_lesson_image_lesson_video_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='learning_le_lesson__038019_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
    ]
