# Generated by Django 5.2.7 on 2025-12-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_remove_lesson_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='learning_le_slug_39551e_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
    ]
