# Generated by Django 5.2.7 on 2025-12-20 14:03

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_remove_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions]),
        ),
    ]
