# Generated by Django 5.2.7 on 2025-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_alter_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes (auto-calculated from video if available)', null=True),
        ),
    ]
