# Generated by Django 5.2.7 on 2025-12-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_lesson_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in minutes (auto-calculated from video if available)', max_digits=6, null=True),
        ),
    ]
