# Generated by Django 5.2.7 on 2025-12-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_alter_lesson_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Lesson Category',
                'verbose_name_plural': 'Lesson Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning.lessoncategory'),
        ),
    ]
