# Generated by Django 5.2.7 on 2025-12-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_lessoncategory_lesson_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncategory',
            options={'ordering': ['name'], 'verbose_name': 'Lesson Category', 'verbose_name_plural': 'Lesson Categories'},
        ),
        migrations.RemoveField(
            model_name='lessoncategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessoncategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lessoncategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lessoncategory',
            name='updated_at',
        ),
    ]
