# Generated by Django 5.2.7 on 2025-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_alter_lessoncategory_options_and_more'),
        ('onboarding', '0007_remove_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Vehicle types for this test. Leave empty for all vehicle types.', related_name='tests', to='onboarding.vehicle'),
        ),
    ]
