# Generated by Django 5.2.7 on 2025-12-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_remove_is_demo'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE learning_question DROP COLUMN IF EXISTS weight;',
            reverse_sql='ALTER TABLE learning_question ADD COLUMN weight INTEGER DEFAULT 1;',
        ),
    ]
