# Generated by Django 5.2.7 on 2026-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_move_explanation_to_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_hy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Chinese)'),
        ),
    ]
