# Generated by Django 5.2.7 on 2026-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_test_description_en_test_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_es',
            field=models.TextField(blank=True, verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_hi',
            field=models.TextField(blank=True, verbose_name='Content (Hindi)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_hy',
            field=models.TextField(blank=True, verbose_name='Content (Armenian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Content (Russian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_zh',
            field=models.TextField(blank=True, verbose_name='Content (Chinese)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_hy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Chinese)'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='name_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Armenian)'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='name_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Chinese)'),
        ),
    ]
