# Generated by Django 5.2.7 on 2026-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_remove_unique_answer_order_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
    ]
