# Generated by Django 5.2.7 on 2026-02-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_alter_test_options_test_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='is_mixed',
            field=models.BooleanField(default=False, help_text='Whether this is a mixed test attempt (questions from multiple tests)'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.test'),
        ),
    ]
