# Generated by Django 5.2.7 on 2026-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0033_remove_mixed_test_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Whether this test is a demo test (accessible without subscription)'),
        ),
    ]
