# Generated by Django 5.2.7 on 2026-05-04 07:13

import django.core.validators
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_test_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the question (WebP only)', null=True, upload_to='test_questions/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])]),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the test (WebP only)', null=True, upload_to='test_images/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])]),
        ),
    ]
