# Generated by Django 5.2.7 on 2026-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_webp_only_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mixed_question_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of random questions to pull from this test for the mixed screening test. Set 0 to exclude.'),
        ),
    ]
