# Generated by Django 5.2.7 on 2026-05-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_add_mixed_question_count_to_cmstest'),
        ('learning', '0036_add_mixed_question_count_to_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='cms_answer',
            field=models.OneToOneField(blank=True, help_text='Link to the CMS answer this was synced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_answer', to='cms.cmsanswer'),
        ),
        migrations.AddField(
            model_name='question',
            name='cms_question',
            field=models.OneToOneField(blank=True, help_text='Link to the CMS question this was synced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_question', to='cms.cmsquestion'),
        ),
        migrations.AddField(
            model_name='test',
            name='cms_test',
            field=models.OneToOneField(blank=True, help_text='Link to the CMS test this was synced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_test', to='cms.cmstest'),
        ),
    ]
