# Generated by Django 5.2.7 on 2026-05-12 18:03

from django.db import migrations


def backfill_cms_links(apps, schema_editor):
    """Link existing learning records to their CMS counterparts by title/text."""
    CMSTest = apps.get_model('cms', 'CMSTest')
    CMSQuestion = apps.get_model('cms', 'CMSQuestion')
    CMSAnswer = apps.get_model('cms', 'CMSAnswer')
    Test = apps.get_model('learning', 'Test')
    Question = apps.get_model('learning', 'Question')
    AnswerOption = apps.get_model('learning', 'AnswerOption')

    # Backfill Test -> CMSTest
    for cms_test in CMSTest.objects.all():
        Test.objects.filter(title=cms_test.title, cms_test__isnull=True).update(
            cms_test=cms_test
        )

    # Backfill Question -> CMSQuestion
    for cms_q in CMSQuestion.objects.select_related('test').all():
        matching_tests = Test.objects.filter(cms_test=cms_q.test_id)
        for test in matching_tests:
            Question.objects.filter(
                test=test, text=cms_q.text, cms_question__isnull=True
            ).update(cms_question=cms_q)

    # Backfill AnswerOption -> CMSAnswer
    for cms_a in CMSAnswer.objects.select_related('question').all():
        matching_questions = Question.objects.filter(cms_question=cms_a.question_id)
        for question in matching_questions:
            AnswerOption.objects.filter(
                question=question, text=cms_a.text, cms_answer__isnull=True
            ).update(cms_answer=cms_a)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_add_cms_foreign_keys'),
        ('cms', '0012_add_mixed_question_count_to_cmstest'),
    ]

    operations = [
        migrations.RunPython(backfill_cms_links, migrations.RunPython.noop),
    ]
