# Generated by Django 5.2.7 on 2026-06-05 08:44

import django.core.validators
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_backfill_cms_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image_es',
            field=models.ImageField(blank=True, help_text='Cover image for the test - Spanish (WebP only)', null=True, upload_to='test_images/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Image (Spanish)'),
        ),
        migrations.AddField(
            model_name='test',
            name='image_hi',
            field=models.ImageField(blank=True, help_text='Cover image for the test - Hindi (WebP only)', null=True, upload_to='test_images/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Image (Hindi)'),
        ),
        migrations.AddField(
            model_name='test',
            name='image_hy',
            field=models.ImageField(blank=True, help_text='Cover image for the test - Armenian (WebP only)', null=True, upload_to='test_images/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Image (Armenian)'),
        ),
        migrations.AddField(
            model_name='test',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Cover image for the test - Russian (WebP only)', null=True, upload_to='test_images/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Image (Russian)'),
        ),
        migrations.AddField(
            model_name='test',
            name='image_zh',
            field=models.ImageField(blank=True, help_text='Cover image for the test - Chinese (WebP only)', null=True, upload_to='test_images/', validators=[learning.models.validate_webp_image, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Image (Chinese)'),
        ),
    ]
