# Generated by Django 5.2.7 on 2026-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_test_image_es_test_image_hi_test_image_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_es',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Spanish)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_hi',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Hindi)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_hy',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Armenian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Russian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_zh',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Chinese)'),
        ),
    ]
