# Generated by Django 5.2.7 on 2026-08-25 16:22

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_test_image_es_test_image_hi_test_image_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_es',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Spanish)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_hi',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Hindi)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_hy',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Armenian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Russian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_zh',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Chinese)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_es',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Spanish)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_hi',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Hindi)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_hy',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Armenian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Russian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_zh',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video (Chinese)'),
        ),
    ]
