# Generated by Django 5.2.7 on 2026-08-20 17:27

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0040_lesson_video_es_lesson_video_hi_lesson_video_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_es',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Spanish)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_hi',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Hindi)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_hy',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Armenian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Russian)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_zh',
            field=models.ImageField(blank=True, help_text='Image must be at least 800x500 pixels', null=True, upload_to='lessons/images/', validators=[learning.models.validate_lesson_image_dimensions], verbose_name='Image (Chinese)'),
        ),
    ]
