# Generated by Django 5.2.7 on 2025-12-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_new', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_period', models.CharField(default='/month', max_length=50)),
                ('save_text', models.CharField(blank=True, max_length=50)),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('button_text', models.CharField(default='Start my plan', max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(choices=[('fa-solid fa-check', 'Check'), ('fa-solid fa-xmark', 'Cross'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-car', 'Car')], default='fa-solid fa-check', help_text='CSS class for the icon (e.g. FontAwesome)', max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.plan')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
