# Generated by Django 5.2.7 on 2025-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(help_text='Client avatar/profile image', upload_to='reviews/avatars/')),
                ('name', models.CharField(help_text="Client name (e.g., 'Bimosaurus')", max_length=100)),
                ('job_title', models.CharField(help_text="Client job title (e.g., 'Graphic Designer')", max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars (1-5)')),
                ('review_text', models.TextField(help_text='The review/testimonial text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review is displayed on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
