# Generated by Django 5.2.7 on 2025-12-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0002_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text="Plan category (e.g., 'STATE-SPECIFIC')", max_length=100)),
                ('title', models.CharField(help_text="Plan name (e.g., '7-Day Express', '30-Day All-Access')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the plan')),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly subscription price', max_digits=6)),
                ('price_one_time', models.DecimalField(decimal_places=2, help_text='One-time payment price', max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text="Discount amount (e.g., 10 for 'Save $10')", max_digits=6)),
                ('button_text', models.CharField(default='Start my plan', help_text='Call-to-action button text', max_length=50)),
                ('button_url', models.CharField(blank=True, help_text='URL or route for the CTA button', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this plan with a border/special styling')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is visible on the site')),
                ('stripe_price_id_monthly', models.CharField(blank=True, help_text='Stripe Price ID for monthly subscription', max_length=255)),
                ('stripe_price_id_one_time', models.CharField(blank=True, help_text='Stripe Price ID for one-time payment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Feature description (e.g., 'All 650 exam-like questions for your state')", max_length=255)),
                ('is_included', models.BooleanField(default=True, help_text='Whether this feature is included (unchecked = grayed out)')),
                ('icon_type', models.CharField(choices=[('check', 'Check Mark (✓)'), ('star', 'Star (⭐)'), ('document', 'Document (📄)'), ('car', 'Car (🚗)'), ('trophy', 'Trophy (🏆)'), ('lock', 'Lock (🔒)'), ('unlock', 'Unlock (🔓)')], default='check', help_text='Icon to display next to the feature', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the plan')),
                ('detail_text', models.TextField(blank=True, help_text='Optional detailed description (shown on hover/click)')),
                ('plan', models.ForeignKey(help_text='The pricing plan this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.pricingplan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
