# Generated by Django 5.2.7 on 2025-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0003_pricingplan_planfeature_delete_feature_delete_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='price_monthly',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='price_one_time',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_new',
            field=models.DecimalField(decimal_places=2, default=0, help_text='New/current price (e.g., $39)', max_digits=6),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_old',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Old/original price (crossed out, e.g., $49)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_period',
            field=models.CharField(default='/month', help_text="Price period text (e.g., '/month')", max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Discount amount shown in badge (e.g., 10 for 'Save $10')", max_digits=6),
        ),
    ]
