# Generated by Django 5.2.7 on 2025-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0004_remove_pricingplan_price_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='icon',
            field=models.ImageField(blank=True, help_text='Custom uploaded icon (overrides icon_type if provided)', null=True, upload_to='plan_features/icons/'),
        ),
    ]
