# Generated by Django 5.2.7 on 2025-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0005_planfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='icon_type',
            field=models.CharField(choices=[('pricing_icons/check.svg', 'Check Mark'), ('pricing_icons/book.svg', 'Book'), ('pricing_icons/shield.svg', 'Shield'), ('pricing_icons/simulation.svg', 'Simulation')], default='pricing_icons/check.svg', help_text='Icon to display next to the feature', max_length=50),
        ),
    ]
