# Generated by Django 5.2.7 on 2025-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0006_alter_planfeature_icon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Contact person's name", max_length=100)),
                ('email', models.EmailField(help_text="Contact person's email address", max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='The message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', help_text='Status of the contact request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created_at',),
            },
        ),
    ]
