# Generated by Django 5.2.7 on 2025-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0008_remove_contact_subject_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(help_text='First line of address (e.g., street address in Armenian)', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Second line of address (e.g., translated address)', max_length=255)),
                ('phone_primary', models.CharField(help_text='Primary phone number (e.g., 011 580606)', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, help_text='Secondary phone number (e.g., 044 580606)', max_length=20)),
                ('email_primary', models.EmailField(help_text='Primary email address (e.g., info@smv.am)', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, help_text='Secondary email address (e.g., nn@consultant.com)', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Only one ContactInfo should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
