# Generated by Django 5.2.7 on 2025-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0009_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Partner logo image', upload_to='partners/logos/')),
                ('name', models.CharField(help_text="Partner name (e.g., 'INECOBANK', 'HSBC')", max_length=100)),
                ('description', models.TextField(help_text="Partner description (e.g., 'Great potential for cooperation with Ineco Bank for over 10 years')")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this partner is displayed on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
