# Generated by Django 5.2.7 on 2025-12-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0010_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
    ]
