# Generated by Django 5.2.7 on 2025-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0011_remove_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Home page hero image (minimum dimensions: 1108x1206 pixels)', upload_to='homepage/images/')),
                ('title', models.CharField(help_text='Main title for the home page hero section', max_length=200)),
                ('description', models.TextField(help_text='Description text for the home page hero section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this home page content is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
