# Generated by Django 5.2.7 on 2025-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0012_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='MainBanner',
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'Main Banner', 'verbose_name_plural': 'Main Banners'},
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(help_text='Main banner hero image (minimum dimensions: 1108x1206 pixels)', upload_to='main_banner/images/'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(help_text='Main title for the main banner hero section', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='description',
            field=models.TextField(help_text='Description text for the main banner hero section'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this main banner content is active'),
        ),
    ]
