# Generated by Django 5.2.7 on 2025-12-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0013_rename_homepage_to_mainbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'ordering': ('-created_at',), 'verbose_name': 'Main Banner', 'verbose_name_plural': 'Main Banners'},
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='order',
        ),
        migrations.AddField(
            model_name='clientreview',
            name='image',
            field=models.ImageField(blank=True, help_text='Client review image (minimum dimensions: 800x600 pixels)', null=True, upload_to='reviews/images/'),
        ),
    ]
