# Generated by Django 5.2.7 on 2025-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0014_alter_mainbanner_options_remove_mainbanner_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='avatar',
            field=models.ImageField(help_text='Client avatar/profile image (minimum dimensions: 112x112 pixels)', upload_to='reviews/avatars/'),
        ),
    ]
