# Generated by Django 5.2.7 on 2025-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0015_alter_clientreview_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='title2',
            field=models.CharField(blank=True, default='', help_text='Secondary title for the main banner hero section', max_length=200),
        ),
    ]
