# Generated by Django 5.2.7 on 2025-12-25 16:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0016_mainbanner_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=modelcluster.fields.ParentalKey(help_text='The pricing plan this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.pricingplan'),
        ),
    ]
