# Generated by Django 5.2.7 on 2025-12-25 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0018_alter_planfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='icon',
            field=models.FileField(blank=True, help_text='Custom SVG icon (overrides icon_type if provided). Upload .svg files only.', null=True, upload_to='plan_features/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
