# Generated by Django 5.2.7 on 2025-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0019_alter_planfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Primary phone number (e.g., 011 580606)', max_length=20),
        ),
    ]
