# Generated by Django 5.2.7 on 2025-12-29 07:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0020_alter_contactinfo_phone_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Background image for the How It Works section (e.g., cars in parking lot)', upload_to='how_it_works/backgrounds/')),
                ('section_header', models.CharField(default='HOW IT WORKS', help_text="Section header text (e.g., 'HOW IT WORKS')", max_length=100)),
                ('title', models.CharField(help_text="Main title (e.g., '4 simple steps to get road-ready')", max_length=200)),
                ('description', models.TextField(help_text="Description text below the title (e.g., 'Remote assistants will work to ensure you can do your job well, regardless of where you are')")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this How It Works section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'How It Works Section',
                'verbose_name_plural': 'How It Works Sections',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('step_number', models.CharField(help_text="Step number (e.g., '01', '02', '03', '04')", max_length=10)),
                ('title', models.CharField(help_text="Step title (e.g., 'Sign up or start for free', 'Choose a test option')", max_length=200)),
                ('description', models.TextField(help_text="Step description (e.g., 'The world's largest and most liquid platform with spot, futures and options trading')")),
                ('icon', models.ImageField(blank=True, help_text='Optional icon/image for this step', null=True, upload_to='how_it_works/step_icons/')),
                ('how_it_works', modelcluster.fields.ParentalKey(help_text='The How It Works section this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_details.howitworks')),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ('sort_order',),
            },
        ),
    ]
