# Generated by Django 5.2.7 on 2025-12-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0021_howitworks_howitworksstep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howitworksstep',
            options={'ordering': ('order',), 'verbose_name': 'How It Works Step', 'verbose_name_plural': 'How It Works Steps'},
        ),
        migrations.RemoveField(
            model_name='howitworksstep',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='how_it_works',
            field=models.ForeignKey(help_text='The How It Works section this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_details.howitworks'),
        ),
    ]
