# Generated by Django 5.2.7 on 2025-12-29 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0022_alter_howitworksstep_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeature',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(help_text='The pricing plan this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.pricingplan'),
        ),
    ]
