# Generated by Django 5.2.7 on 2026-01-08 10:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0023_remove_planfeature_sort_order_alter_planfeature_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howitworksstep',
            name='how_it_works',
            field=modelcluster.fields.ParentalKey(help_text='The How It Works section this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_details.howitworks'),
        ),
    ]
