# Generated by Django 5.2.7 on 2026-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0024_alter_howitworksstep_how_it_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text="Partner's official website URL (e.g., 'https://www.partner.com')", max_length=500),
        ),
    ]
