# Generated by Django 5.2.7 on 2026-01-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0025_partner_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text='Button URL or link', max_length=500),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='button_name',
            field=models.CharField(blank=True, default='', help_text="Button text (e.g., 'Video Guide')", max_length=100),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text1',
            field=models.CharField(blank=True, default='', help_text="First statistic text (e.g., '2200+ Success attempts')", max_length=100),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text2',
            field=models.CharField(blank=True, default='', help_text="Second statistic text (e.g., '2350+ Success attempts')", max_length=100),
        ),
    ]
