# Generated by Django 5.2.7 on 2026-01-09 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0026_mainbanner_button_link_mainbanner_button_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='video',
            field=models.FileField(blank=True, help_text="Optional video file (mp4, webm, ogg, mov, avi). Button link will be auto-set to this video's URL.", null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text='Button URL or link (auto-filled if video is uploaded)', max_length=500),
        ),
    ]
