# Generated by Django 5.2.7 on 2026-01-09 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0027_mainbanner_video_alter_mainbanner_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='video',
            field=models.FileField(blank=True, help_text="Optional video file (webm only). Button link will be auto-set to this video's URL.", null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])]),
        ),
    ]
