# Generated by Django 5.2.7 on 2026-01-09 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0028_alter_mainbanner_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='use_video_as_button_link',
            field=models.BooleanField(default=False, help_text='If checked, video upload is required'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text='Button URL or link', max_length=500),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video file (webm only)', null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])]),
        ),
    ]
