# Generated by Django 5.2.7 on 2026-01-09 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0029_mainbanner_use_video_as_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text='Button URL or link (required if video is not uploaded)', max_length=500),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_name',
            field=models.CharField(default='', help_text="Button text (e.g., 'Video Guide')", max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='stat_text1',
            field=models.CharField(default='', help_text="First statistic text (e.g., '2200+ Success attempts')", max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='stat_text2',
            field=models.CharField(default='', help_text="Second statistic text (e.g., '2350+ Success attempts')", max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='video',
            field=models.FileField(blank=True, help_text='Video file - webm only (required if button link is not set)', null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])]),
        ),
    ]
