# Generated by Django 5.2.7 on 2026-01-09 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0030_alter_mainbanner_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text="Button URL or link (required if 'Use video as button link' is unchecked)", max_length=500),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='use_video_as_button_link',
            field=models.BooleanField(default=False, help_text='Check to use video as button link (makes video required). Uncheck to use button link (makes button link required).'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='video',
            field=models.FileField(blank=True, help_text="Video file - webm only (required if 'Use video as button link' is checked)", null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])]),
        ),
    ]
