# Generated by Django 5.2.7 on 2026-01-09 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0031_alter_mainbanner_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(default='TRUST & SAFETY', help_text="Section header text (e.g., 'TRUST & SAFETY')", max_length=100)),
                ('title', models.CharField(help_text="Main title (e.g., 'It's fast and profitable with us')", max_length=200)),
                ('image', models.ImageField(help_text='Main image for the Trust & Safety section (minimum dimensions: 800x600 pixels)', upload_to='trust_safety/images/')),
                ('video_button_text', models.CharField(default='Go through video tutorials', help_text="Video button text (e.g., 'Go through video tutorials')", max_length=100)),
                ('video_button_link', models.CharField(blank=True, default='', help_text="Video button URL or link (required if 'Use video file' is unchecked)", max_length=500)),
                ('video', models.FileField(blank=True, help_text="Video file - webm or mp4 (required if 'Use video file' is checked)", null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])])),
                ('use_video_file', models.BooleanField(default=False, help_text='Check to use video file (makes video required). Uncheck to use video button link (makes link required).')),
                ('registration_button_text', models.CharField(default='Start Registration', help_text="Registration button text (e.g., 'Start Registration')", max_length=100)),
                ('registration_button_link', models.CharField(default='', help_text='Registration button URL or link', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Trust & Safety section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trust & Safety Section',
                'verbose_name_plural': 'Trust & Safety Sections',
            },
        ),
        migrations.CreateModel(
            name='TrustSafetyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Feature number (e.g., '1', '2', '3')", max_length=10)),
                ('title', models.CharField(help_text="Feature title (e.g., 'Updated questionnaire', 'From the official database')", max_length=200)),
                ('description', models.TextField(help_text="Feature description (e.g., 'Lorem ipsum dolor sit amet consectetur. Auctor')")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('trust_safety', models.ForeignKey(help_text='The Trust & Safety section this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.trustsafety')),
            ],
            options={
                'verbose_name': 'Trust & Safety Feature',
                'verbose_name_plural': 'Trust & Safety Features',
                'ordering': ('order',),
            },
        ),
    ]
