# Generated by Django 5.2.7 on 2026-01-09 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0032_trustsafety_trustsafetyfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustsafety',
            name='registration_button_link',
        ),
        migrations.RemoveField(
            model_name='trustsafety',
            name='registration_button_text',
        ),
        migrations.RemoveField(
            model_name='trustsafety',
            name='use_video_file',
        ),
        migrations.RemoveField(
            model_name='trustsafety',
            name='video_button_link',
        ),
        migrations.RemoveField(
            model_name='trustsafety',
            name='video_button_text',
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='button_link',
            field=models.CharField(default='', help_text='Button URL or link', max_length=500),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='button_text',
            field=models.CharField(default='Start Registration', help_text="Button text (e.g., 'Start Registration')", max_length=100),
        ),
        migrations.AlterField(
            model_name='trustsafety',
            name='video',
            field=models.FileField(blank=True, help_text='Video file - webm or mp4 format', null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])]),
        ),
    ]
