# Generated by Django 5.2.7 on 2026-01-09 14:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0033_remove_trustsafety_registration_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustsafetyfeature',
            name='trust_safety',
            field=modelcluster.fields.ParentalKey(help_text='The Trust & Safety section this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.trustsafety'),
        ),
    ]
