# Generated by Django 5.2.7 on 2026-01-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0034_alter_trustsafetyfeature_trust_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reach your success in three steps.', help_text="Main title (e.g., 'Reach your success in three steps.')", max_length=200)),
                ('description', models.TextField(help_text="Description text below the title (e.g., 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...')")),
                ('button_text', models.CharField(default='DEMO TEST', help_text="Button text (e.g., 'DEMO TEST')", max_length=100)),
                ('button_link', models.CharField(default='', help_text='Button URL or link', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Success Steps section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Success Steps Section',
                'verbose_name_plural': 'Success Steps Sections',
            },
        ),
        migrations.CreateModel(
            name='SuccessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Icon/image for this step (e.g., sign up icon, practice icon, exam icon)', upload_to='success_steps/icons/')),
                ('title', models.CharField(help_text="Step title (e.g., 'Sign Up in Seconds', 'Practice All Tests', 'Pass Your Exam')", max_length=200)),
                ('description', models.TextField(help_text="Step description (e.g., 'Enter your name, email and password.')")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('success_steps', models.ForeignKey(help_text='The Success Steps section this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_details.successsteps')),
            ],
            options={
                'verbose_name': 'Success Step',
                'verbose_name_plural': 'Success Steps',
                'ordering': ('order',),
            },
        ),
    ]
