# Generated by Django 5.2.7 on 2026-01-09 14:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0035_successsteps_successstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstep',
            name='success_steps',
            field=modelcluster.fields.ParentalKey(help_text='The Success Steps section this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_details.successsteps'),
        ),
    ]
