# Generated by Django 5.2.7 on 2026-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0036_alter_successstep_success_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='button_name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='button_name_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='button_name_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Name (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='button_name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Name (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='button_name_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Name (Chinese)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text1_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 1 (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text1_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 1 (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text1_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 1 (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text1_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 1 (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text1_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 1 (Chinese)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text2_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 2 (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text2_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 2 (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text2_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 2 (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text2_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 2 (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='stat_text2_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat Text 2 (Chinese)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title2_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secondary Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title2_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secondary Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title2_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secondary Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secondary Title (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title2_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secondary Title (Chinese)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)'),
        ),
    ]
