# Generated by Django 5.2.7 on 2026-01-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0037_add_multilingual_fields_to_mainbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='howitworks',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='section_header_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section Header (Spanish)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='section_header_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section Header (Hindi)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='section_header_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section Header (Armenian)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='section_header_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section Header (Russian)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='section_header_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section Header (Chinese)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)'),
        ),
    ]
