# Generated by Django 5.2.7 on 2026-01-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0038_add_multilingual_fields_to_howitworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstep',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='title_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='successstep',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='button_text_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='button_text_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Text (Russian)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='button_text_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Text (Chinese)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='title_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='successsteps',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)'),
        ),
    ]
