# Generated by Django 5.2.7 on 2026-01-16 07:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0040_add_multilingual_fields_to_trustsafety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=modelcluster.fields.ParentalKey(help_text='The pricing plan this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_details.pricingplan'),
        ),
    ]
