# Generated by Django 5.2.7 on 2026-01-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0041_pricing_plan_clusterablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='detail_text_es',
            field=models.TextField(blank=True, verbose_name='Detail Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='detail_text_hi',
            field=models.TextField(blank=True, verbose_name='Detail Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='detail_text_hy',
            field=models.TextField(blank=True, verbose_name='Detail Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='detail_text_ru',
            field=models.TextField(blank=True, verbose_name='Detail Text (Russian)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='detail_text_zh',
            field=models.TextField(blank=True, verbose_name='Detail Text (Chinese)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_hy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Russian)'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Chinese)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text_hi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text_hy',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Text (Russian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text_zh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Text (Chinese)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_period_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price Period (Spanish)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_period_hi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price Period (Hindi)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_period_hy',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price Period (Armenian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_period_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price Period (Russian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_period_zh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Price Period (Chinese)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle (Spanish)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle (Hindi)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='subtitle_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle (Armenian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle (Russian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='subtitle_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle (Chinese)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Chinese)'),
        ),
    ]
