# Generated by Django 5.2.7 on 2026-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0042_add_multilingual_fields_to_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='job_title_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='job_title_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='job_title_hy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='job_title_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title (Russian)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='job_title_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title (Chinese)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_text_es',
            field=models.TextField(blank=True, verbose_name='Review Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_text_hi',
            field=models.TextField(blank=True, verbose_name='Review Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_text_hy',
            field=models.TextField(blank=True, verbose_name='Review Text (Armenian)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_text_ru',
            field=models.TextField(blank=True, verbose_name='Review Text (Russian)'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_text_zh',
            field=models.TextField(blank=True, verbose_name='Review Text (Chinese)'),
        ),
    ]
