# Generated by Django 5.2.7 on 2026-01-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0043_add_multilingual_fields_to_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reach your success in three steps.', help_text="Main title (e.g., 'Reach your success in three steps.')", max_length=200)),
                ('description', models.TextField(help_text='Description text below the title')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('title_hy', models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)')),
                ('description_hy', models.TextField(blank=True, verbose_name='Description (Armenian)')),
                ('title_hi', models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)')),
                ('description_es', models.TextField(blank=True, verbose_name='Description (Spanish)')),
                ('title_zh', models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)')),
                ('description_zh', models.TextField(blank=True, verbose_name='Description (Chinese)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Learning Options section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Options Section',
                'verbose_name_plural': 'Learning Options Sections',
            },
        ),
        migrations.CreateModel(
            name='LearningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for this option card', upload_to='learning_options/images/')),
                ('title', models.CharField(help_text="Option title (e.g., 'Start Test', 'Practice Test', 'Real Exam Simul.', 'By Topic')", max_length=200)),
                ('description', models.TextField(help_text="Option description (e.g., '650+ exam-like questions', 'Road Signs, Rules, Fines')")),
                ('link', models.CharField(blank=True, default='', help_text='Optional URL or route for this option card', max_length=500)),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('title_hy', models.CharField(blank=True, max_length=200, verbose_name='Title (Armenian)')),
                ('description_hy', models.TextField(blank=True, verbose_name='Description (Armenian)')),
                ('title_hi', models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)')),
                ('description_es', models.TextField(blank=True, verbose_name='Description (Spanish)')),
                ('title_zh', models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)')),
                ('description_zh', models.TextField(blank=True, verbose_name='Description (Chinese)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('learning_options', models.ForeignKey(help_text='The Learning Options section this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='site_details.learningoptions')),
            ],
            options={
                'verbose_name': 'Learning Option',
                'verbose_name_plural': 'Learning Options',
                'ordering': ('order',),
            },
        ),
    ]
