# Generated by Django 5.2.7 on 2026-01-21 12:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0044_learningoptions_learningoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoption',
            name='learning_options',
            field=modelcluster.fields.ParentalKey(help_text='The Learning Options section this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='site_details.learningoptions'),
        ),
    ]
