# Generated by Django 5.2.7 on 2026-02-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0044_create_pricing_plans'),
        ('site_details', '0045_alter_learningoption_learning_options'),
    ]

    operations = [
    ]
