# Generated by Django 5.2.7 on 2026-02-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0046_merge_20260215_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstep',
            name='link',
            field=models.CharField(blank=True, default='', help_text="Link/path for this step (e.g., '/signup', 'https://example.com')", max_length=500),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='avatar',
            field=models.ImageField(help_text='Client avatar/profile image (exact dimensions: 300x300 pixels).', upload_to='reviews/avatars/'),
        ),
    ]
