# Generated by Django 5.2.7 on 2026-02-27 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0047_add_link_to_successstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Social network name (e.g., 'Facebook', 'Instagram', 'Twitter')", max_length=100)),
                ('icon', models.FileField(blank=True, help_text='Social network icon (SVG, PNG, JPG, or WebP)', null=True, upload_to='social_networks/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('url', models.URLField(help_text="Social network profile URL (e.g., 'https://facebook.com/yourpage')", max_length=500)),
                ('hide', models.BooleanField(default=False, help_text='Hide this social network link from the frontend')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this social network is available on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
