# Generated by Django 5.2.7 on 2026-08-07 11:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0048_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Column title (e.g., 'Navigation', 'Work Process')", max_length=100)),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Title (Russian)')),
                ('title_hy', models.CharField(blank=True, max_length=100, verbose_name='Title (Armenian)')),
                ('title_hi', models.CharField(blank=True, max_length=100, verbose_name='Title (Hindi)')),
                ('title_es', models.CharField(blank=True, max_length=100, verbose_name='Title (Spanish)')),
                ('title_zh', models.CharField(blank=True, max_length=100, verbose_name='Title (Chinese)')),
                ('hide', models.BooleanField(default=False, help_text='Hide this column from the frontend')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this footer column is available on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Column',
                'verbose_name_plural': 'Footer Columns',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Link label (e.g., 'Home', 'About Us', 'Premium')", max_length=200)),
                ('label_ru', models.CharField(blank=True, max_length=200, verbose_name='Label (Russian)')),
                ('label_hy', models.CharField(blank=True, max_length=200, verbose_name='Label (Armenian)')),
                ('label_hi', models.CharField(blank=True, max_length=200, verbose_name='Label (Hindi)')),
                ('label_es', models.CharField(blank=True, max_length=200, verbose_name='Label (Spanish)')),
                ('label_zh', models.CharField(blank=True, max_length=200, verbose_name='Label (Chinese)')),
                ('url', models.CharField(help_text="Link URL - can be a relative path (e.g., '/about') or a full URL (e.g., 'https://example.com')", max_length=500)),
                ('hide', models.BooleanField(default=False, help_text='Hide this link from the frontend')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this footer link is available on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', modelcluster.fields.ParentalKey(help_text='The footer column this link belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_details.footercolumn')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
