# Generated by Django 5.2.7 on 2026-08-25 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0050_seed_footer_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='main_banner/images/', verbose_name='Image (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='image_hi',
            field=models.ImageField(blank=True, null=True, upload_to='main_banner/images/', verbose_name='Image (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='image_hy',
            field=models.ImageField(blank=True, null=True, upload_to='main_banner/images/', verbose_name='Image (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='main_banner/images/', verbose_name='Image (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='image_zh',
            field=models.ImageField(blank=True, null=True, upload_to='main_banner/images/', verbose_name='Image (Chinese)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='video_es',
            field=models.FileField(blank=True, null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Video (Spanish)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='video_hi',
            field=models.FileField(blank=True, null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Video (Hindi)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='video_hy',
            field=models.FileField(blank=True, null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Video (Armenian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Video (Russian)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='video_zh',
            field=models.FileField(blank=True, null=True, upload_to='main_banner/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Video (Chinese)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='trust_safety/images/', verbose_name='Image (Spanish)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='image_hi',
            field=models.ImageField(blank=True, null=True, upload_to='trust_safety/images/', verbose_name='Image (Hindi)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='image_hy',
            field=models.ImageField(blank=True, null=True, upload_to='trust_safety/images/', verbose_name='Image (Armenian)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='trust_safety/images/', verbose_name='Image (Russian)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='image_zh',
            field=models.ImageField(blank=True, null=True, upload_to='trust_safety/images/', verbose_name='Image (Chinese)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='video_es',
            field=models.FileField(blank=True, null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])], verbose_name='Video (Spanish)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='video_hi',
            field=models.FileField(blank=True, null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])], verbose_name='Video (Hindi)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='video_hy',
            field=models.FileField(blank=True, null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])], verbose_name='Video (Armenian)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])], verbose_name='Video (Russian)'),
        ),
        migrations.AddField(
            model_name='trustsafety',
            name='video_zh',
            field=models.FileField(blank=True, null=True, upload_to='trust_safety/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4'])], verbose_name='Video (Chinese)'),
        ),
    ]
