# Generated by Django 5.2.7 on 2025-12-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_profile_age_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='image',
            field=models.CharField(blank=True, help_text='Path to the knowledge level image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
    ]
