# Generated by Django 5.2.7 on 2025-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_knowledge_image_knowledge_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload knowledge level icon', null=True, upload_to='knowledge/'),
        ),
    ]
