# Generated by Django 5.2.7 on 2025-12-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_knowledge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload vehicle type icon', null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
    ]
