# Generated by Django 5.2.7 on 2025-12-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_vehicle_image_vehicle_image_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='knowledge',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
