# Generated by Django 5.2.7 on 2026-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_remove_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name_es',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_hi',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_hy',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Armenian)'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_zh',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Chinese)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_es',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_hi',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_hy',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Armenian)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_zh',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Chinese)'),
        ),
    ]
